### ISSUE TITLE
Extend profiler with more data sources

### ISSUE THREAD

**Issue by msoechting** [TeamTetris/tetris-game#22]

**Comment by julianweise** [comment]
- [x] GeoLocation
- [x] Camera and Face++
- [] User-Agent
- [] Passport DB

**Comment by julianweise** [comment]
Any other data sources? Feel free to edit my list @msoechting @Johannes-Schneider @friedow

**Comment by msoechting** [comment]
How about ethnicity distribution statistics for single countries?
