### ISSUE TITLE
functional battle royale

### ISSUE THREAD

**Issue by julianweise** [TeamTetris/tetris-game#38]
- [x] [M] Consider Self-Eliminations -> Client sends '**selfEliminated**' to Server
- [x] [M] Set appropriate state when receiving Elimination Notice as a client
- [x] [C] Display time until match start -> ideally dont use same timer widget
- [x] [M] Clear field on match start client-side
- [ ] [C] Visualize eliminations on remote & own fields
- [x] [C] Scoreboard: Display and Update with Names & Points (and endangered status)
- [x] [C] Scoreboard: Visualize eliminations
- [x] [C] Send name on JoinMatch socket (field name: '**displayName**')
- [ ] [MC] Visualize wins (golden blocks)
- [ ] [M] Shader Background -> parametrize speed with game progress (estimate with alive players/all players)
- [ ] [MC] Clarify which remote fields are displayed
- [x] [C] Clear field (at match start) not when already eliminated
- [x] [C] Clear points on match start

Server:
- [x] [M] Process name on MatchJoin socket
- [x] [M] Mark players as endangered
- [x] [M] Self-Identification of Clients -> send socket id on connect to client
- [x] [M] Consider self-eliminations in elimination planning (edge case: last remaining would be eliminated)
- [x] [M] Smart placements: have self-eliminated & disconnected players drop to the lowest available rank

**Comment by msoechting** [comment]
Done:
- Send SocketID on Connect to Client (event name is 'yourSocketId' with body: { yourSocketId: abc123 })
- Mark players as endangered
- Self-eliminations (server-side): TODO: Client should send event 'selfEliminated' to server when this happens.
- Consider self-eliminations in elimination planning (For this, I extended PlayStatus to [Playing, Eliminated, **Won**])

Also:
- Stagger network updates from server, i.e. send updates every 250ms (if changes happened)

**Comment by msoechting** [comment]
Done: 
- Consider Self-Eliminations -> Client sends 'selfEliminated' to Server
- Set appropriate state when receiving Elimination Notice as a client
- Clear field on match start client-side

**Comment by msoechting** [comment]
fixed in #48
